[package]
name = "ginkou-loader"
version = "0.1.0"
authors = ["nullchinchilla <nullchinchilla@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wry="0.9.4"
anyhow="1"
argh="0.1.4"
urlencoding="1"
scopeguard="1"
dirs="3"