[package]
name = "ginkou-loader"
version = "0.1.0"
authors = ["nullchinchilla <nullchinchilla@pm.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wry={version="0.12.2", default-features=false, features=["file-drop", "protocol"]}
anyhow="1"
argh="0.1.4"
urlencoding="1"
scopeguard="1"
dirs="3"
# mime-sniffer = "0.1"
tide="0.16"
smol="1"