name: Test

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Update Apt
        run: sudo apt update

      - name: Install Dependencies
        run: sudo apt -y install libgtk-3-dev libsoup2.4-dev libwebkit2gtk-4.0-dev

      - name: Run Tests
        run: cargo test --locked --verbose